/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bookaroom.gui;
import com.mycompany.bookaroom.entity.Campus;
import com.mycompany.bookaroom.entity.Reserva;
import com.mycompany.bookaroom.entity.Funcionario;
import com.mycompany.bookaroom.entity.Sala;
import com.mycompany.bookaroom.entity.Predio;
import com.mycompany.bookaroom.entity.Equipamento;
import com.mycompany.bookaroom.entity.Disponibilidade;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre Vinicius
 */
public class Home extends javax.swing.JFrame {
    
    private static ArrayList<Funcionario> lstFuncionarios;
    
    private static ArrayList<Sala> lstSalas;

    private static ArrayList<Equipamento> lstEquipamentos;    
    
    private static ArrayList<Disponibilidade> lstDisponibilidades;
    
    private DefaultTableModel tabelaModelo = new DefaultTableModel();
    /**
     * Creates new form TelaLogin
     */
    public Home() {
       
        initComponents();
        
        lstFuncionarios.forEach(funcionario -> {
            cbxFuncionario.addItem(funcionario);
        });
        
        lstSalas.forEach(sala -> {
            cbxSala.addItem(sala);
        });
        
        lstEquipamentos.forEach(equipamento -> {
            cbxEquipamento.addItem(equipamento);
        });

        tabelaModelo.addColumn("Data");
        tabelaModelo.addColumn("Sala");
        tabelaModelo.addColumn("Predio");
        tabelaModelo.addColumn("Campus");
        tabelaModelo.addColumn("HorarioInicio");
        tabelaModelo.addColumn("HorarioFim");
        //tabelaModelo.
        
        tblHorarios.setModel(tabelaModelo);
        DefaultTableModel model = (DefaultTableModel) tblHorarios.getModel();
        String data = cldCalendario.getDate().toString();
        model.addRow(new Object[]{data, "Column 2", "Column 3","Column 4","Column 5","Column 6"});
        
        tblHorarios.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuEditar = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblCalendar = new javax.swing.JLabel();
        cbxHoraInicio = new javax.swing.JComboBox<>();
        lblHoraInicio = new javax.swing.JLabel();
        lblHoraFim = new javax.swing.JLabel();
        cbxHoraFim = new javax.swing.JComboBox<>();
        lblReservas = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        cbxFuncionario = new javax.swing.JComboBox<>();
        chbEquipamento = new javax.swing.JCheckBox();
        btnListarReservas = new javax.swing.JButton();
        txtAssunto = new javax.swing.JTextField();
        cbxSala = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHorarios = new javax.swing.JTable();
        cldCalendario = new com.toedter.calendar.JDateChooser();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblHorarios = new javax.swing.JLabel();
        lblCampus = new javax.swing.JLabel();
        lblEquipamento = new javax.swing.JLabel();
        lblSala = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblAssunto = new javax.swing.JLabel();
        rdbMoc = new javax.swing.JRadioButton();
        rdbJanuaria = new javax.swing.JRadioButton();
        cbxEquipamento = new javax.swing.JComboBox<>();

        mnuEditar.setMnemonic('e');
        mnuEditar.setText("Editar");
        jPopupMenu1.add(mnuEditar);

        mnuExcluir.setMnemonic('x');
        mnuExcluir.setText("Excluir");
        jPopupMenu1.add(mnuExcluir);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setSize(new java.awt.Dimension(1200, 800));

        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHome.setText("Home");

        lblCalendar.setText("Cadastro de Reserva");

        cbxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00","10:00", "11:00", "12:00", "13:00","14:00", "15:00", "16:00", "17:00","18:00", "19:00", "20:00", "21:00"}));
        cbxHoraInicio.setSelectedIndex(0);
        cbxHoraInicio.setToolTipText("");
        cbxHoraInicio.setEnabled(false);
        cbxHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHoraInicioActionPerformed(evt);
            }
        });

        lblHoraInicio.setText("Inicio");

        lblHoraFim.setText("Fim");

        cbxHoraFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00","10:00", "11:00", "12:00", "13:00","14:00", "15:00", "16:00", "17:00","18:00", "19:00", "20:00", "21:00", "22:00"}));
        cbxHoraFim.setEnabled(false);
        cbxHoraFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHoraFimActionPerformed(evt);
            }
        });

        lblReservas.setText("Horários");

        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        cbxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncionarioActionPerformed(evt);
            }
        });

        chbEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbEquipamentoActionPerformed(evt);
            }
        });

        btnListarReservas.setText("Listar Reservas");
        btnListarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarReservasActionPerformed(evt);
            }
        });

        txtAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssuntoActionPerformed(evt);
            }
        });

        cbxSala.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbxSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSalaActionPerformed(evt);
            }
        });

        tblHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblHorarios);

        cldCalendario.setDate(new Date());
        cldCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cldCalendarioMouseClicked(evt);
            }
        });

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        lblHorarios.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblHorarios.setText("Horários");
        lblHorarios.setToolTipText("");

        lblCampus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblCampus.setText("Campus");
        lblCampus.setToolTipText("");

        lblEquipamento.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblEquipamento.setText("Equipamento");
        lblEquipamento.setToolTipText("");

        lblSala.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSala.setText("Sala");
        lblSala.setToolTipText("");

        lblFuncionario.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFuncionario.setText("Funcionário");
        lblFuncionario.setToolTipText("");

        lblAssunto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblAssunto.setText("Assunto");
        lblAssunto.setToolTipText("");

        buttonGroup1.add(rdbMoc);
        rdbMoc.setSelected(true);
        rdbMoc.setText("Moc");
        rdbMoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMocActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbJanuaria);
        rdbJanuaria.setText("Januária");

        cbxEquipamento.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbxEquipamento.setEnabled(false);

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(lblHome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lblReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCalendar)
                .addGap(221, 221, 221))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(btnListarReservas)
                        .addGap(43, 43, 43)
                        .addComponent(btnReservar))
                    .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(lblHoraInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lblHoraFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(chbEquipamento)
                        .addGap(18, 18, 18)
                        .addComponent(cbxEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSala, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cldCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rdbMoc)
                        .addGap(77, 77, 77)
                        .addComponent(rdbJanuaria)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReservas)
                    .addComponent(lblCalendar))
                .addGap(15, 15, 15)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(cldCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHorarios)
                        .addGap(8, 8, 8)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoraInicio)
                            .addComponent(cbxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraFim)
                            .addComponent(cbxHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCampus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbMoc)
                            .addComponent(rdbJanuaria))
                        .addGap(2, 2, 2)
                        .addComponent(lblEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbEquipamento)
                            .addComponent(cbxEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSala))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(cbxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAssunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarReservas)
                    .addComponent(btnReservar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSalaActionPerformed

    private void txtAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssuntoActionPerformed

    private void btnListarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarReservasActionPerformed
        // TODO add your handling code here:
        new ListarReservas().setVisible(true);
    }//GEN-LAST:event_btnListarReservasActionPerformed

    private void chbEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbEquipamentoActionPerformed
        // TODO add your handling code here:
        cbxEquipamento.setEnabled(true);
    }//GEN-LAST:event_chbEquipamentoActionPerformed

    private void cbxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncionarioActionPerformed
        // Code adding the component to the parent container - not shown here
    }//GEN-LAST:event_cbxFuncionarioActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        Reserva reserva = new Reserva(LocalDate.parse(cldCalendario.getDate().toString()),
                LocalTime.parse(cbxHoraInicio.getSelectedItem().toString()),
                LocalTime.parse(cbxHoraFim.getSelectedItem().toString()),
                txtAssunto.getText(),
                cbxSala.getItemAt(cbxSala.getSelectedIndex()),
                cbxEquipamento.getItemAt(cbxEquipamento.getSelectedIndex()));
        /*
        reserva.criarReserva(LocalDate.parse(cldCalendario.getDate().toString()),
            LocalTime.parse(cbxHoraInicio.getSelectedItem().toString()),
            LocalTime.MIN,
            txtAssunto.getText(),
            cbxSala.getSelectedItem().toString());
        */
    }//GEN-LAST:event_btnReservarActionPerformed

    private void cbxHoraFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHoraFimActionPerformed
        // TODO add your handling code here:
        cbxHoraInicio = new javax.swing.JComboBox<>();

        cbxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00","10:00", "11:00", "12:00", "13:00","14:00", "15:00", "16:00", "17:00","18:00", "19:00", "20:00", "21:00", "22:00"}));
    }//GEN-LAST:event_cbxHoraFimActionPerformed

    private void cbxHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxHoraInicioActionPerformed
        // TODO add your handling code here:
        cbxHoraInicio = new javax.swing.JComboBox<>();

        cbxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00","10:00", "11:00", "12:00", "13:00","14:00", "15:00", "16:00", "17:00","18:00", "19:00", "20:00", "21:00"}));
    }//GEN-LAST:event_cbxHoraInicioActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        cbxHoraInicio.setEnabled(true);
        cbxHoraFim.setEnabled(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cldCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cldCalendarioMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1){
            
        }
    }//GEN-LAST:event_cldCalendarioMouseClicked

    private void rdbMocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Campus ifnmg = new Campus("IF","2","300","Village","Moc","MG");
        
        Predio predioSuperior = new Predio("Predio Superior",ifnmg);
        
        Funcionario f1 = new Funcionario("Lucio","Professor","2020",ifnmg);
        Funcionario f2 = new Funcionario("Renato","Diretor","1010",ifnmg);
        Funcionario f3 = new Funcionario("Seu Afonso","Terceirizado","1510",ifnmg);
        
        Sala sala1 = new Sala(1,50,predioSuperior);
        Sala sala2 = new Sala(2,30,predioSuperior);
        Sala sala3 = new Sala(3,30,predioSuperior);
        Sala sala4 = new Sala(4,30,predioSuperior);
        
        Equipamento eq1 = new Equipamento("Martelo","IFNMG",predioSuperior);
        Equipamento eq2 = new Equipamento("Controle TV","IFNMG",predioSuperior);
        Equipamento eq3 = new Equipamento("Chave Fixa","IFNMG",predioSuperior);
        Equipamento eq4 = new Equipamento("Parafuso","IFNMG",predioSuperior);
        
        // Adicionando funcionario
        ifnmg.adicionarFuncionario(f1);
        ifnmg.adicionarFuncionario(f2);
        ifnmg.adicionarFuncionario(f3);
        
        // Adicionando sala
        ifnmg.adicionarSala(sala1);
        ifnmg.adicionarSala(sala2);
        ifnmg.adicionarSala(sala3);
        ifnmg.adicionarSala(sala4);
        
        // Adicionando equipamentos
        predioSuperior.adicionarEquipamento(eq1);
        predioSuperior.adicionarEquipamento(eq2);
        predioSuperior.adicionarEquipamento(eq3);
        predioSuperior.adicionarEquipamento(eq4);
        
        lstFuncionarios = ifnmg.getFuncionarios();
        lstEquipamentos = predioSuperior.getEquipamentos();
        lstSalas = ifnmg.getSalas();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarReservas;
    private javax.swing.JButton btnReservar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Equipamento> cbxEquipamento;
    private javax.swing.JComboBox<Object> cbxFuncionario;
    private javax.swing.JComboBox<String> cbxHoraFim;
    private javax.swing.JComboBox<String> cbxHoraInicio;
    private javax.swing.JComboBox<Sala> cbxSala;
    private javax.swing.JCheckBox chbEquipamento;
    private com.toedter.calendar.JDateChooser cldCalendario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAssunto;
    private javax.swing.JLabel lblCalendar;
    private javax.swing.JLabel lblCampus;
    private javax.swing.JLabel lblEquipamento;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHoraFim;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblReservas;
    private javax.swing.JLabel lblSala;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JRadioButton rdbJanuaria;
    private javax.swing.JRadioButton rdbMoc;
    private javax.swing.JTable tblHorarios;
    private javax.swing.JTextField txtAssunto;
    // End of variables declaration//GEN-END:variables
}
